controller_list:
  - name: fake_g1_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - left_shoulder_pitch_joint
      - left_shoulder_roll_joint
      - left_shoulder_yaw_joint
      - left_elbow_joint
      - left_wrist_roll_joint
      - left_wrist_pitch_joint
      - left_wrist_yaw_joint
  - name: fake_g1_left_hand_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_g1_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - right_shoulder_pitch_joint
      - right_shoulder_roll_joint
      - right_shoulder_yaw_joint
      - right_elbow_joint
      - right_wrist_roll_joint
      - right_wrist_pitch_joint
      - right_wrist_yaw_joint
  - name: fake_g1_right_hand_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: g1_left_arm
    pose: g1_left_arm_home
  - group: g1_right_arm
    pose: g1_right_arm_home
