g1_left_arm:
  # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
  max_cache_size: 1000
  min_pose_distance: 1
  min_joint_config_distance: 4
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  goal_joint_tolerance: 0.0001
  goal_position_tolerance: 0.0001
  goal_orientation_tolerance: 0.001
  # minimal_displacement_weight: 0.1
  # center_joints_weight: 0.1
  # avoid_joint_limits_weight: 0.5
g1_right_arm:
  # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
  max_cache_size: 1000
  min_pose_distance: 1
  min_joint_config_distance: 4
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  goal_joint_tolerance: 0.0001
  goal_position_tolerance: 0.0001
  goal_orientation_tolerance: 0.001
  # minimal_displacement_weight: 0.1
  # center_joints_weight: 0.1
  # avoid_joint_limits_weight: 0.5
